use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing manifest dir"));
    let agents_dir = manifest_dir.join("src/agents");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));

    println!("cargo:rerun-if-changed={}", agents_dir.display());

    let mut modules: Vec<String> = fs::read_dir(&agents_dir)
        .expect("failed to read src/agents")
        .filter_map(|entry| entry.ok())
        .filter_map(|entry| {
            let path = entry.path();
            println!("cargo:rerun-if-changed={}", path.display());
            let ext = path.extension()?.to_str()?;
            if ext != "rs" {
                return None;
            }
            let stem = path.file_stem()?.to_str()?;
            if stem == "mod" {
                return None;
            }
            Some(stem.to_string())
        })
        .collect();

    modules.sort();

    let mut generated = String::from("// @generated by build.rs\n");
    for module in &modules {
        let module_path = agents_dir.join(format!("{module}.rs"));
        generated.push_str(&format!(
            "#[path = r#\"{}\"#]\nmod {};\n",
            module_path.display(),
            module
        ));
    }
    generated.push_str("\npub(crate) static GENERATED_REGISTRY: &[&dyn AgentPlugin] = &[\n");
    for module in &modules {
        generated.push_str(&format!("    &{}::PLUGIN,\n", module));
    }
    generated.push_str("];\n");

    fs::write(out_dir.join("agents_registry.rs"), generated)
        .expect("failed to write generated agents registry");
}
